-- Per-team bullpen leverage profiles. Backend-only: the simulation reads the multipliers and
-- a Claude-assisted or official update replaces them, with every change recorded as an event.
create table if not exists public.team_bullpen (
  id integer generated by default as identity primary key,
  team_id integer not null unique references public.teams(id),
  high_leverage_multiplier double precision not null default 1.0,
  middle_multiplier double precision not null default 1.0,
  chase_multiplier double precision not null default 1.0,
  mop_up_multiplier double precision not null default 1.0,
  high_leverage_arms json not null default '[]'::json,
  middle_arms json not null default '[]'::json,
  chase_arms json not null default '[]'::json,
  mop_up_arms json not null default '[]'::json,
  source varchar(16) not null default 'DERIVED',
  note text,
  revision integer not null default 1,
  updated_at timestamptz not null
);

create index if not exists ix_team_bullpen_team_id on public.team_bullpen(team_id);

create table if not exists public.team_bullpen_events (
  id integer generated by default as identity primary key,
  team_id integer not null references public.teams(id),
  revision integer not null,
  source varchar(16) not null,
  changes json not null,
  note text,
  created_at timestamptz not null
);

create index if not exists ix_team_bullpen_events_team_id on public.team_bullpen_events(team_id);
create index if not exists ix_team_bullpen_events_created_at on public.team_bullpen_events(created_at);

alter table public.team_bullpen enable row level security;
alter table public.team_bullpen_events enable row level security;
revoke all on table public.team_bullpen, public.team_bullpen_events from anon, authenticated;
