-- Per-batter base-state splits behind the plate-appearance engine. Backend-only: counting stats
-- are stored rather than rates so thin exact states can be shrunk toward larger samples at read
-- time. States are BASES_EMPTY, RUNNER_1/2/3/12/13/23, BASES_LOADED and SCORING_POSITION.
create table if not exists public.batter_splits (
  id integer generated by default as identity primary key,
  league varchar(8) not null,
  season integer not null,
  player_id varchar(24) not null,
  player_name varchar(80),
  state varchar(20) not null,
  at_bats integer not null default 0,
  hits integer not null default 0,
  doubles integer not null default 0,
  triples integer not null default 0,
  home_runs integer not null default 0,
  walks integer not null default 0,
  hit_by_pitch integer not null default 0,
  strikeouts integer not null default 0,
  sacrifice_flies integer not null default 0,
  grounded_into_double_play integer not null default 0,
  source varchar(80) not null,
  source_url text not null,
  collected_at timestamptz not null,
  unique (league, season, player_id, state)
);

create index if not exists ix_batter_splits_league on public.batter_splits(league);
create index if not exists ix_batter_splits_season on public.batter_splits(season);
create index if not exists ix_batter_splits_player_id on public.batter_splits(player_id);

alter table public.batter_splits enable row level security;
revoke all on table public.batter_splits from anon, authenticated;
