-- Archived game starters with their strictly-prior season totals. Backend-only.
-- Without this the replay archive has no pre-game starter data at all, leaving every starter
-- feature constant and unlearnable.
create table if not exists public.game_starters (
  id integer generated by default as identity primary key,
  game_id integer not null references public.games(id),
  side varchar(4) not null,
  player_id varchar(24) not null,
  name varchar(80),
  prior_games integer not null default 0,
  prior_starts integer not null default 0,
  prior_innings double precision not null default 0,
  prior_earned_runs integer not null default 0,
  prior_hits integer not null default 0,
  prior_walks integer not null default 0,
  prior_strikeouts integer not null default 0,
  prior_home_runs integer not null default 0,
  prior_quality_starts integer not null default 0,
  source varchar(80) not null,
  source_url text not null,
  collected_at timestamptz not null,
  unique (game_id, side)
);

create index if not exists ix_game_starters_game_id on public.game_starters(game_id);
create index if not exists ix_game_starters_player_id on public.game_starters(player_id);

alter table public.game_starters enable row level security;
revoke all on table public.game_starters from anon, authenticated;
