-- Backend-only champion/challenger model registry.
create table if not exists public.model_artifacts (
  id integer generated by default as identity primary key,
  model_version_id integer not null unique references public.model_versions(id),
  league varchar(8) not null,
  feature_names json not null,
  feature_means json not null,
  feature_scales json not null,
  win_intercept double precision not null,
  win_coefficients json not null,
  home_run_intercept double precision not null,
  home_run_coefficients json not null,
  away_run_intercept double precision not null,
  away_run_coefficients json not null,
  training_cutoff timestamptz not null,
  training_sample_size integer not null,
  validation_metrics json not null,
  created_at timestamptz not null
);

create index if not exists ix_model_artifacts_model_version_id on public.model_artifacts(model_version_id);
create index if not exists ix_model_artifacts_league on public.model_artifacts(league);
create index if not exists ix_model_artifacts_training_cutoff on public.model_artifacts(training_cutoff);
create index if not exists ix_model_artifacts_created_at on public.model_artifacts(created_at);

create table if not exists public.model_registry (
  league varchar(8) primary key,
  champion_model_version_id integer references public.model_versions(id),
  previous_model_version_id integer references public.model_versions(id),
  promoted_at timestamptz,
  last_evaluated_at timestamptz,
  policy json not null
);

create table if not exists public.model_lifecycle_events (
  id integer generated by default as identity primary key,
  league varchar(8) not null,
  event_type varchar(24) not null,
  candidate_model_version_id integer references public.model_versions(id),
  champion_model_version_id integer references public.model_versions(id),
  sample_size integer not null,
  metrics json not null,
  reason text not null,
  created_at timestamptz not null
);

create index if not exists ix_model_lifecycle_events_league on public.model_lifecycle_events(league);
create index if not exists ix_model_lifecycle_events_event_type on public.model_lifecycle_events(event_type);
create index if not exists ix_model_lifecycle_events_created_at on public.model_lifecycle_events(created_at);

alter table public.model_artifacts enable row level security;
alter table public.model_registry enable row level security;
alter table public.model_lifecycle_events enable row level security;
revoke all on table public.model_artifacts, public.model_registry, public.model_lifecycle_events from anon, authenticated;
